### ISSUE TITLE
获取response headers异常

### ISSUE THREAD

**Issue by ChuangSR** [TheWeiJun/scrapy-cloudflare#1]
![1d74269e-4836-4d6b-8723-d5522fd98b07](https://github.com/TheWeiJun/scrapy-cloudflare/assets/145638759/a11152c5-ecf7-4b57-8c7c-d43d671e0b14)

**Comment by ChuangSR** [comment]
![3ac69492-8548-4146-bd73-f18a7a536693](https://github.com/TheWeiJun/scrapy-cloudflare/assets/145638759/bc6e7a0e-bd8b-45d0-ac52-c304de566108)

**Comment by ChuangSR** [comment]
![1efa0d00-57f4-4b5e-8a53-be2b686e3790](https://github.com/TheWeiJun/scrapy-cloudflare/assets/145638759/eba2252a-0b29-4491-9a1a-fc4737f6ce8d)

**Comment by ChuangSR** [comment]
在使用https://github.com/tieyongjie/scrapy-fingerprint  时也出现了该问题，解决方案较为粗暴，直接将headers加入meta中

**Comment by TheWeiJun** [comment]
使用方式还是不太对，可以看下公众号的使用案例再试试。

**Comment by ChuangSR** [comment]
使用项目的示例代码运行仍然出现该问题
![7366aed6-5fa8-425b-9cda-7270203d910f](https://github.com/TheWeiJun/scrapy-cloudflare/assets/145638759/6a9bba78-7366-49dc-a242-7731dda3913a)
![26f34244-d590-42df-8d4f-ff7422ca7b18](https://github.com/TheWeiJun/scrapy-cloudflare/assets/145638759/3d0f17d8-96b6-496d-8a3c-2a0d0ba15b18)

**Comment by TheWeiJun** [comment]
<img width="1032" alt="image" src="https://github.com/TheWeiJun/scrapy-cloudflare/assets/32383804/e3da49c3-df56-4cd4-bada-b03968891695">
你这个问题是因为headers参数同url编码不一致导致的，解决方法如下：

1、将accept-language注释掉
2、或者将url设置为https://www.weights.gg/zh
